site_name: Iuncterra
theme: torillic
docs_dir: source
site_dir: docs

nav:
  - ...

hooks:
  - utils/ipa.py

exclude_docs: |
  desktop.ini

markdown_extensions:
  - nl2br
  - extra
  - wikilinks

plugins:
  - awesome-pages
