site_name: Iuncterra
theme: 
  name: torillic
  background_image: bg.jpg
docs_dir: source
site_dir: docs
site_url: https://TEParsons.github.io/Iuncterra

nav:
  - ...

extra_css:
  - extra.css

hooks:
  - utils/statblocks.py
  - utils/ipa.py
  - utils/links.py
  - utils/tables.py

exclude_docs: |
  desktop.ini

validation:
  absolute_links: ignore

markdown_extensions:
  - nl2br
  - extra
  - wikilinks

plugins:
  - awesome-pages
  - mermaid2
