name: Pages
on:
  push:
    branches:
    - autocompile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@autocompile
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown
    - name: Build and Commit
      run: python compile
    - name: Push changes
      uses: ad-m/github-push-action@autocompile
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
