name: Sanitize
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Checkout branch
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Sanitize
      run: |
        python "utils/sanitize.py"
    - name: Commit
      run: |
        git config --global user.email "todd.e.parsons@googlemail.com"
        git config --global user.name "Todd Parsons"
        git add --all
        git commit --all -m "Sanitize filenames"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
